# -*- coding: utf-8 -*-
"""ANN Practical Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMBydR--H3MHoNcBTl6s2kBwvwTXL-i2
"""

import numpy as np

def linear_threshold_gate(dot, T):
    if dot >= T:
        return 1
    else:
        return 0

input_table = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

weights = np.array([1, 1])
T = 1
dot_products = input_table @ weights

for i in range(len(input_table)):
    activation = linear_threshold_gate(dot_products[i], T)
    print(f"Input {input_table[i]} -> Output {activation}")