# -*- coding: utf-8 -*-
"""ANN Practical Assignment 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WM-gDP78ZvN17pYf38HnRFJCI9mCilfe
"""

import numpy as np

class ART1:
    def __init__(self, input_size, max_clusters, vigilance):
        self.rho = vigilance
        self.input_size = input_size
        self.max_clusters = max_clusters
        self.t = np.ones((max_clusters, input_size))
        self.b = np.full((max_clusters, input_size), 1 / (1 + input_size))
        self.n_clusters = 0

    def compute_similarity(self, x, cluster_idx):
        intersection = np.logical_and(x, self.t[cluster_idx])
        if np.sum(x) == 0:
            return 1.0
        return np.sum(intersection) / np.sum(x)

    def train(self, x):
        if self.n_clusters == 0:
            self.t[0] = x
            self.b[0] = x / (0.5 + np.sum(x))
            self.n_clusters = 1
            return 0

        scores = [np.dot(self.b[i], x) for i in range(self.n_clusters)]
        sorted_indices = np.argsort(scores)[::-1]

        for idx in sorted_indices:
            if self.compute_similarity(x, idx) >= self.rho:
                intersection = np.logical_and(x, self.t[idx])
                self.t[idx] = intersection
                self.b[idx] = intersection / (0.5 + np.sum(intersection))
                return idx

        if self.n_clusters < self.max_clusters:
            new_idx = self.n_clusters
            self.t[new_idx] = x
            self.b[new_idx] = x / (0.5 + np.sum(x))
            self.n_clusters += 1
            return new_idx

        return -1

patterns = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
art = ART1(input_size=2, max_clusters=4, vigilance=0.9)

print("Pattern Clustering Results:")
for p in patterns:
    cluster = art.train(p)
    print(f"Input: {p} -> Assigned to Cluster: {cluster}")