# -*- coding: utf-8 -*-
"""ANN Practical Assignment 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9D0eFkaAWQ3Ca3d08aEPqH9hB4DNkDy
"""

import numpy as np

class HopfieldNetwork:
    def __init__(self, n_neurons):
        self.n_neurons = n_neurons
        self.weights = np.zeros((n_neurons, n_neurons))

    def train(self, patterns):
        for pattern in patterns:
            self.weights += np.outer(pattern, pattern)
        np.fill_diagonal(self.weights, 0)

    def predict(self, pattern):
        raw_output = np.dot(self.weights, pattern)
        prediction = np.sign(raw_output)
        prediction[prediction == 0] = -1
        return prediction

if __name__ == "__main__":
    patterns = np.array([
        [1, 1, -1, -1],
        [-1, -1, 1, 1],
        [1, 1, 1, -1],
        [-1, 1, 1, 1]
    ])

    network = HopfieldNetwork(n_neurons=4)
    network.train(patterns)

    for pattern in patterns:
        prediction = network.predict(pattern)
        print(f'Input pattern: {pattern}')
        print(f'Predicted pattern: {prediction.astype(float)}')