# -*- coding: utf-8 -*-
"""ANN Practical Assignment 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhsV-m9YOrMgLsFkTcxz_CoP7vFUuEkB
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
expected_output = np.array([[0], [1], [1], [0]])

epochs = 10000
lr = 0.1
loss_history = []

hidden_weights = np.random.uniform(size=(2,2))
hidden_bias = np.random.uniform(size=(1,2))
output_weights = np.random.uniform(size=(2,1))
output_bias = np.random.uniform(size=(1,1))

print("Training Network...")

for epoch in range(epochs):
    hidden_layer_activation = np.dot(inputs, hidden_weights) + hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)
    output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
    predicted_output = sigmoid(output_layer_activation)

    error = expected_output - predicted_output
    loss = np.mean(np.square(error))
    loss_history.append(loss)

    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

print("Training Complete.\n")
print("Final Predicted XOR Outputs:")
print(predicted_output)

plt.figure(figsize=(8,5))
plt.plot(range(epochs), loss_history, color='blue')
plt.title('Backpropagation Error Convergence (XOR)')
plt.xlim(0, 10000)
plt.xlabel('Epochs')
plt.ylabel('Mean Squared Error')
plt.grid(True)
plt.show()