# -*- coding: utf-8 -*-
"""ANN Practical Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S32A3gdAZYJHoaxIm2deonHvLTLIbTvG
"""

import numpy as np

X = []
Y = []

for i in range(10):
    binary = [int(bit) for bit in format(ord(str(i)), '08b')]
    X.append(binary)
    Y.append(i % 2)

X = np.array(X)
Y = np.array(Y)
weights = np.zeros(8)
bias = 0
learning_rate = 0.5
epochs = 20

for epoch in range(epochs):
    for i in range(len(X)):
        net_input = np.dot(X[i], weights) + bias
        prediction = 1 if net_input >= 0 else 0
        error = Y[i] - prediction
        if error != 0:
            weights += learning_rate * error * X[i]
            bias += learning_rate * error

print(f"{'Digit':<8} | {'Binary ASCII':<12} | {'Prediction':<10}")
print("-" * 38)

for i in range(10):
    net_input = np.dot(X[i], weights) + bias
    prediction = 1 if net_input >= 0 else 0
    result = "Odd" if prediction == 1 else "Even"
    binary_str = "".join(map(str, X[i]))
    print(f"{i:<8} | {binary_str:<12} | {result:<10}")