# -*- coding: utf-8 -*-
"""ANN Practical Assignment 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-p9WLeSOaJF9h-8E3geLBPL8t2C2FFo
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=50):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for _ in range(self.epochs):
            for xi, target in zip(X, y):
                update = self.lr * (target - self.predict(xi))
                self.weights += update * xi
                self.bias += update

    def predict(self, X):
        z = np.dot(X, self.weights) + self.bias
        return np.where(z >= 0, 1, 0)

iris = load_iris()
X = iris.data[:100, [0, 2]]
y = iris.target[:100]

model = Perceptron(learning_rate=0.1, epochs=10)
model.fit(X, y)

x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.02),
                     np.arange(y_min, y_max, 0.02))

Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

plt.figure(figsize=(10, 6))
plt.contourf(xx, yy, Z, alpha=0.3, cmap='Paired')
plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='k', cmap='Paired')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Length (cm)')
plt.title('Refined Perceptron Decision Regions (Iris Dataset)')
plt.show()