# -*- coding: utf-8 -*-
"""ANN Practical Assignment 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PT16C-XiT_FwDfM0Y5BQsUZI3nUZGGBK
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras.optimizers import Adam

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0

model = Sequential([
    Input(shape=(28, 28)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("--- Starting Training ---")
model.fit(X_train, y_train, batch_size=64, epochs=10, verbose=1)

print("\n--- Final Evaluation ---")
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

